import { SecurityPattern } from "../types/index.js";

export const aiPatterns: SecurityPattern[] = [
  {
    id: "AI_PROMPT_INJECTION_DIRECT_INPUT",
    regex: /(?:prompt|messages?|input)\s*[:=]\s*(?:`[^`]*\$\{[^}]*?(?:req\.|request\.|ctx\.request|input|user|message|query|body)|(?:req\.|request\.|input|user|message|query|body)[^,\n;]*$)/i,
    severity: "high",
    category: "ai",
    cweId: "CWE-74",
    message: "Untrusted user input appears to flow directly into an LLM prompt or message body.",
    remediation: "Separate system instructions from user input, constrain untrusted content, and apply prompt-injection defenses before sending data to the model.",
    languages: ["javascript", "typescript", "python"],
  },
  {
    id: "AI_PROMPT_TEMPLATE_USER_INPUT",
    regex: /(?:openai|anthropic|client\.responses|chat\.completions|generateContent|invoke)\s*\([\s\S]{0,120}(?:`[^`]*\$\{[^}]*?(?:req\.|request\.|input|user|message|query|body))/i,
    severity: "high",
    category: "ai",
    cweId: "CWE-74",
    message: "User-controlled data is interpolated into an LLM call payload.",
    remediation: "Treat user content as data, not instructions. Use strict message separation and sanitize or label untrusted content before interpolation.",
    languages: ["javascript", "typescript"],
  },
  {
    id: "AI_OUTPUT_TO_EVAL",
    // `\beval` and `new Function`, not bare `eval|Function`: without the
    // boundary the alternation matched the tail of any identifier, so
    // `isFunction(Response)` in axios was reported as critical LLM-output
    // execution. The property-access tail is what the real case looks like -
    // `eval(completion.choices[0].message.content)` - which the old pattern,
    // requiring a bare identifier before `)`, could not match at all.
    regex: /(?:\beval|\bnew\s+Function)\s*\(\s*(?:llm|model|assistant|response|completion|result|output)[A-Za-z0-9_]*(?:\.[A-Za-z0-9_]+|\[\d+\])*\s*[,)]/i,
    severity: "critical",
    category: "ai",
    cweId: "CWE-95",
    message: "LLM output is executed as code. This can lead to remote code execution.",
    remediation: "Never execute raw model output. Parse structured data only, validate it against a strict schema, and avoid dynamic code execution entirely.",
    languages: ["javascript", "typescript", "python"],
  },
  {
    id: "AI_OUTPUT_TO_SHELL",
    regex: /(?:exec|execSync|spawn|spawnSync|subprocess\.(?:run|call|Popen))\s*\([\s\S]{0,80}(?:llm|model|assistant|response|completion|result|output)/i,
    severity: "critical",
    category: "ai",
    cweId: "CWE-78",
    message: "LLM output is passed to a shell or process execution API.",
    remediation: "Do not convert model output directly into shell commands. Map model output onto a fixed allowlist of safe actions and arguments.",
    languages: ["javascript", "typescript", "python"],
  },
  {
    id: "AI_OUTPUT_TO_HTML",
    regex: /(?:innerHTML|outerHTML|dangerouslySetInnerHTML|document\.write)\s*(?:=|\()\s*(?:llm|model|assistant|response|completion|result|output)/i,
    severity: "high",
    category: "ai",
    cweId: "CWE-79",
    message: "LLM output is rendered into HTML without sanitization.",
    remediation: "Render model output as plain text by default. If HTML is required, sanitize it with a well-tested library before rendering.",
    languages: ["javascript", "typescript"],
  },
  {
    id: "AI_SECRET_IN_CONTEXT",
    regex: /(?:messages?|prompt|context|system)\s*[:=][\s\S]{0,120}(?:api[_-]?key|secret|token|password|private[_-]?key|authorization)/i,
    severity: "high",
    category: "ai",
    cweId: "CWE-201",
    message: "Sensitive values appear to be included in LLM prompt or context construction.",
    remediation: "Never send raw secrets, tokens, or credentials to an LLM. Redact sensitive values before prompt construction.",
    languages: ["javascript", "typescript", "python"],
  },
  {
    id: "AI_SECRET_VARIABLE_IN_PROMPT",
    regex: /(?:prompt|messages?|context)\s*[:=]\s*`[\s\S]{0,200}\$\{[^}]*?(?:secret|token|password|api[_-]?key|authorization)[^}]*\}/i,
    severity: "high",
    category: "ai",
    cweId: "CWE-201",
    message: "A variable that looks like a secret is interpolated into an LLM prompt or context.",
    remediation: "Remove secrets from prompts and redact credentials before constructing LLM input.",
    languages: ["javascript", "typescript"],
  },
  {
    id: "AI_OUTPUT_TO_TEMPLATE_RESPONSE",
    regex: /(?:res\.send|return)\s*\(\s*`[\s\S]{0,120}\$\{(?:llm|model|assistant|response|completion|result|output)[^}]*\}[\s\S]{0,120}`\s*\)/i,
    severity: "high",
    category: "ai",
    cweId: "CWE-79",
    message: "LLM output is interpolated into an HTML/template response without sanitization.",
    remediation: "Treat model output as untrusted content. Escape or sanitize it before including it in rendered templates or responses.",
    languages: ["javascript", "typescript"],
  },
];
