import { SecurityPattern } from "../types/index.js";

export const authPatterns: SecurityPattern[] = [
  {
    id: "JWT_NO_VERIFY",
    regex: /jwt\.decode\s*\((?!.*verify)/i,
    severity: "critical",
    category: "auth",
    cweId: "CWE-347",
    message: "JWT decoded without verification. jwt.decode() does NOT validate the signature.",
    remediation: "Use jwt.verify(token, secret) instead of jwt.decode().",
    languages: ["javascript", "typescript"],
  },
  {
    id: "JWT_NONE_ALGORITHM",
    regex: /algorithms?\s*:\s*\[?\s*['"]none['"]/i,
    severity: "critical",
    category: "auth",
    cweId: "CWE-327",
    message: "JWT 'none' algorithm allowed. Disables token verification entirely.",
    remediation: "Never allow 'none'. Set: { algorithms: ['HS256'] }.",
    languages: ["javascript", "typescript", "python"],
    matchScope: "literal",
  },
  {
    id: "HARDCODED_JWT_SECRET",
    regex: /jwt\.sign\s*\(\s*\{[^}]*\}\s*,\s*['"][^'"]{3,}['"]/i,
    severity: "high",
    category: "auth",
    cweId: "CWE-798",
    message: "Hardcoded JWT signing secret.",
    remediation: "Use env variable: jwt.sign(payload, process.env.JWT_SECRET).",
    languages: ["javascript", "typescript"],
    matchScope: "literal",
  },
  {
    id: "BCRYPT_LOW_ROUNDS",
    regex: /(?:bcrypt|bcryptjs)\.(?:hash|hashSync)\s*\([^,]+,\s*([1-9])\s*\)/,
    severity: "medium",
    category: "auth",
    cweId: "CWE-916",
    message: "bcrypt with fewer than 10 salt rounds. Brute-force risk.",
    remediation: "Use at least 12 rounds: bcrypt.hash(password, 12).",
    languages: ["javascript", "typescript"],
  },
  {
    id: "SESSION_NO_SECURE",
    regex: /session\s*\(\s*\{[^}]*(?:secure\s*:\s*false|httpOnly\s*:\s*false)/i,
    severity: "high",
    category: "auth",
    cweId: "CWE-614",
    message: "Session cookie missing secure/httpOnly flags.",
    remediation: "Set secure: true, httpOnly: true, sameSite: 'strict'.",
    languages: ["javascript", "typescript"],
  },
  {
    id: "CORS_CREDENTIALS_WILDCARD",
    regex: /credentials\s*:\s*true[\s\S]{0,200}origin\s*:\s*(?:true|['"]?\*['"]?)/i,
    severity: "high",
    category: "auth",
    cweId: "CWE-942",
    message: "CORS with credentials + wildcard origin. Any site can make authenticated requests.",
    remediation: "Use a specific origin allowlist when credentials: true.",
    languages: ["javascript", "typescript"],
    matchScope: "literal",
  },
];
