import { SecurityPattern } from "../types/index.js";

export const iacPatterns: SecurityPattern[] = [
  {
    id: "IAC_DOCKERFILE_EXPLICIT_ROOT_USER",
    regex: /^\s*USER\s+(?:root|0)\b/im,
    severity: "high",
    category: "iac",
    cweId: "CWE-250",
    message: "The container explicitly runs as root. Create and select an unprivileged user before the final runtime instruction.",
    remediation: "Add an unprivileged user (e.g. USER node or USER python) in the Dockerfile before the CMD/ENTRYPOINT instructions.",
    languages: ["docker"],
  },
  {
    id: "IAC_DOCKERFILE_REMOTE_ADD",
    regex: /^\s*ADD\s+https?:\/\//im,
    severity: "medium",
    category: "iac",
    cweId: "CWE-494",
    message: "Dockerfile ADD downloads a remote resource without an integrity check. Fetch a pinned artifact and verify its checksum instead.",
    remediation: "Use curl or wget within a RUN instruction, download a specific version, and verify its hash/checksum.",
    languages: ["docker"],
  },
  {
    id: "IAC_DOCKERFILE_CURL_PIPE_SHELL",
    regex: /^\s*RUN\s+.*(?:curl|wget)\b.*\|\s*(?:ba)?sh\b/im,
    severity: "high",
    category: "iac",
    cweId: "CWE-494",
    message: "A downloaded script is piped directly to a shell during the image build. Download a pinned artifact, verify its checksum, and execute it explicitly.",
    remediation: "Download the script, verify the checksum, check the script contents, and then execute it instead of piping directly.",
    languages: ["docker"],
  },
  {
    id: "IAC_CONTAINER_PRIVILEGED_MODE",
    regex: /^\s*privileged\s*:\s*true\b/im,
    severity: "high",
    category: "iac",
    cweId: "CWE-250",
    message: "A container is configured as privileged. Remove privileged mode and grant only the minimal Linux capabilities required.",
    remediation: "Set privileged: false or remove the line entirely, and configure specific capabilities under cap_add if required.",
    languages: ["yaml"],
  },
  {
    id: "IAC_KUBERNETES_HOST_NETWORK",
    regex: /^\s*hostNetwork\s*:\s*true\b/im,
    severity: "high",
    category: "iac",
    cweId: "CWE-668",
    message: "A workload enables host networking. Isolate the workload with normal pod networking.",
    remediation: "Remove hostNetwork: true to isolate the container namespace from the host networking namespace.",
    languages: ["yaml"],
  },
  {
    id: "IAC_KUBERNETES_HOST_PID",
    regex: /^\s*hostPID\s*:\s*true\b/im,
    severity: "high",
    category: "iac",
    cweId: "CWE-250",
    message: "A workload shares the host PID namespace. Disable hostPID.",
    remediation: "Remove hostPID: true to keep the container process namespace isolated from the host.",
    languages: ["yaml"],
  },
  {
    id: "IAC_KUBERNETES_ALLOW_PRIVILEGE_ESCALATION",
    regex: /^\s*allowPrivilegeEscalation\s*:\s*true\b/im,
    severity: "high",
    category: "iac",
    cweId: "CWE-250",
    message: "A container permits privilege escalation. Set allowPrivilegeEscalation to false.",
    remediation: "Explicitly set allowPrivilegeEscalation: false in the securityContext of the container.",
    languages: ["yaml"],
  },
  // Tying an open CIDR to the port it exposes needs two lines of a security
  // group, and this engine matches one line at a time. That correlation lives
  // in rules/sentinel-iac.yml, where Semgrep can see the whole block:
  // sentinel.iac.terraform.public-ssh-security-group and its RDP counterpart.
  // What one line can prove is the open CIDR itself.
  {
    id: "IAC_TERRAFORM_PUBLIC_INGRESS_CIDR",
    regex: /cidr_blocks\s*=\s*\[[^\]]*["'](?:0\.0\.0\.0\/0|::\/0)["']/im,
    severity: "high",
    category: "iac",
    cweId: "CWE-284",
    message: "A security-group rule accepts traffic from every address on the Internet. Restrict the CIDR block to the networks that need access.",
    remediation: "Replace 0.0.0.0/0 (or ::/0) with the specific CIDR ranges that require access, or front the resource with a managed access path such as AWS Systems Manager Session Manager.",
    languages: ["terraform"],
    matchScope: "literal",
  },
  {
    id: "IAC_TERRAFORM_S3_PUBLIC_ACLS",
    regex: /block_public_acls\s*=\s*false\b/im,
    severity: "high",
    category: "iac",
    cweId: "CWE-284",
    message: "AWS S3 public ACL blocking is disabled. Keep public-access blocks enabled.",
    remediation: "Set block_public_acls = true on the aws_s3_bucket_public_access_block resource.",
    languages: ["terraform"],
  },
  {
    id: "IAC_GITHUB_ACTIONS_UNPINNED_ACTION",
    // The optional "- " matters: `- uses: actions/checkout@v4` is the inline
    // list-item form most workflows use, and `^\s*uses:` alone misses it.
    regex: /^\s*(?:-\s+)?uses:\s*[^@\s]+@(?![A-Fa-f0-9]{40}(?:\s|$))[^\s#]+/m,
    severity: "medium",
    category: "iac",
    cweId: "CWE-494",
    message: "A GitHub Action is referenced by a mutable tag or branch. Pin third-party actions to a full commit SHA.",
    remediation: "Use a full 40-character commit SHA instead of a branch/tag name (e.g. uses: actions/checkout@v4 -> uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11).",
    languages: ["yaml"],
  },
  {
    id: "IAC_GITHUB_ACTIONS_PULL_REQUEST_TARGET",
    regex: /^\s*pull_request_target\s*:/m,
    severity: "high",
    category: "iac",
    cweId: "CWE-269",
    message: "pull_request_target runs with base-repository privileges. Do not check out or execute untrusted pull-request code in this workflow.",
    remediation: "Avoid using pull_request_target unless absolutely necessary, and never checkout the pull request branch directly with it.",
    languages: ["yaml"],
  },
  {
    id: "IAC_GITHUB_ACTIONS_ECHO_SECRET",
    regex: /^\s*(?:echo|printf)\b.*\$\{\{\s*secrets\./m,
    severity: "critical",
    category: "iac",
    cweId: "CWE-200",
    message: "A GitHub Actions step writes a repository secret to command output.",
    remediation: "Do not write secrets to console outputs or logs. Pass them as environment variables to scripts that require them.",
    languages: ["yaml"],
  },
];
