import { SecurityPattern } from "../types/index.js";

export const miscPatterns: SecurityPattern[] = [
  {
    id: "CORS_WILDCARD",
    regex: /(?:Access-Control-Allow-Origin|origin)\s*[:=]\s*['"]?\*/i,
    severity: "medium",
    category: "miscellaneous",
    cweId: "CWE-942",
    message: "CORS wildcard '*' allows any domain to make requests to your API.",
    remediation: "Restrict to specific trusted origins: origin: ['https://yourdomain.com'].",
    languages: ["*"],
    matchScope: "literal",
  },
  {
    id: "CSRF_DISABLED",
    regex: /csrf\s*[:=]\s*false|csurf.*disable/i,
    severity: "high",
    category: "miscellaneous",
    cweId: "CWE-352",
    message: "CSRF protection appears disabled. State-changing requests can be forged.",
    remediation: "Enable CSRF protection for all state-changing endpoints. Use csurf middleware or SameSite cookies.",
    languages: ["javascript", "typescript"],
  },
  {
    id: "HTTP_NO_TLS",
    regex: /http:\/\/(?!localhost|127\.0\.0\.1|0\.0\.0\.0|::1|schemas?\.|www\.w3\.org|xml\.org|example\.com|placeholder|fonts\.googleapis|cdn\.|unpkg|jsdelivr)/,
    severity: "low",
    category: "miscellaneous",
    cweId: "CWE-319",
    message: "Non-localhost HTTP URL detected. Data transmitted without encryption.",
    remediation: "Use HTTPS for all non-localhost connections.",
    languages: ["*"],
  },
  {
    id: "DEBUG_MODE_PROD",
    // `1` is anchored with \b so `debug: 10` — a log-level constant — no longer
    // matches as `debug: 1`.
    regex: /(?:^|[^\w.])(?:DEBUG|debug)\s*[:=]\s*(?:true\b|1\b|['"]true['"])|app\.set\s*\(\s*['"]env['"]\s*,\s*['"]development['"]\)/i,
    severity: "medium",
    category: "miscellaneous",
    cweId: "CWE-489",
    message: "Debug mode may be enabled. Debug info can leak internal details to attackers.",
    remediation: "Ensure DEBUG is disabled in production. Use environment-based config.",
    languages: ["*"],
    matchScope: "literal",
  },
  {
    id: "STACK_TRACE_LEAK",
    regex: /(?:res\.(?:send|json)\s*\(\s*(?:err|error)\.(?:stack|message)|console\.(?:log|error)\s*\(\s*(?:err|error)\.stack)/,
    severity: "medium",
    category: "miscellaneous",
    cweId: "CWE-209",
    message: "Error stack trace may be exposed to clients. Leaks internal paths and code structure.",
    remediation: "Log errors server-side. Send generic error messages to clients in production.",
    languages: ["javascript", "typescript"],
  },
  {
    id: "OPEN_REDIRECT",
    regex: /(?:redirect|location)\s*(?:\(|=)\s*(?:req\.|params\.|query\.|body\.|input|user)/i,
    severity: "medium",
    category: "miscellaneous",
    cweId: "CWE-601",
    message: "Open redirect: user input controls redirect destination. Phishing risk.",
    remediation: "Validate redirect URLs against a whitelist of allowed domains.",
    languages: ["javascript", "typescript", "python"],
  },

  {
    id: "RATE_LIMIT_MISSING",
    regex: /app\.(?:post|put|patch|delete)\s*\(\s*['"]\/(?:login|auth|register|signup|reset|forgot)/i,
    severity: "medium",
    category: "miscellaneous",
    cweId: "CWE-307",
    message: "Auth endpoint without apparent rate limiting. Brute-force risk.",
    remediation: "Add rate limiting: npm install express-rate-limit. Apply to auth routes.",
    languages: ["javascript", "typescript"],
    matchScope: "literal",
  },
];
