import { SecurityPattern } from "../types/index.js";

/**
 * Python security patterns, covering Django, Flask, FastAPI, SQLAlchemy,
 * Jinja2, pickle, and subprocess.
 */
export const pythonPatterns: SecurityPattern[] = [
  // SQL Injection (Python)
  {
    id: "PY_SQL_INJECTION_FORMAT",
    regex: /(?:execute|cursor\.execute|raw|rawsql)\s*\(\s*(?:f['"]|['"].*?%s.*?%|['"].*?\.format\(|['"].*?\+)/i,
    severity: "critical",
    category: "injection",
    cweId: "CWE-89",
    message: "Python SQL injection: string formatting in SQL query. Use parameterized queries.",
    remediation: "Use parameterized queries: cursor.execute('SELECT * FROM users WHERE id = %s', (user_id,))",
    languages: ["python"],
    matchScope: "literal",
  },
  {
    id: "PY_SQLALCHEMY_TEXT_RAW",
    regex: /(?:text|TextClause)\s*\(\s*f['"]|\.from_statement\s*\(\s*f['"]/i,
    severity: "high",
    category: "injection",
    cweId: "CWE-89",
    message: "SQLAlchemy raw SQL with f-string. Use bound parameters.",
    remediation: "Use: text('SELECT * FROM users WHERE id = :id').bindparams(id=user_id)",
    languages: ["python"],
  },
  {
    id: "PY_DJANGO_RAW_SQL",
    regex: /\.raw\s*\(\s*f['"]|\.extra\s*\(\s*(?:where|select)\s*=\s*\[?\s*f['"]/i,
    severity: "critical",
    category: "injection",
    cweId: "CWE-89",
    message: "Django raw SQL with f-string interpolation. Use params argument.",
    remediation: "Use: Model.objects.raw('SELECT * FROM app_model WHERE id = %s', [user_id])",
    languages: ["python"],
  },

  // Command Injection (Python)
  {
    id: "PY_OS_SYSTEM",
    regex: /os\.system\s*\(\s*(?:f['"]|.*?\+|.*?\.format\(|.*?%\s)/,
    severity: "critical",
    category: "injection",
    cweId: "CWE-78",
    message: "os.system() with dynamic input. Full shell injection risk.",
    remediation: "Use subprocess.run() with a list and shell=False: subprocess.run(['cmd', arg])",
    languages: ["python"],
  },
  {
    id: "PY_SUBPROCESS_SHELL",
    regex: /subprocess\.(?:call|run|Popen|check_output|check_call)\s*\([^)]*shell\s*=\s*True/i,
    severity: "high",
    category: "injection",
    cweId: "CWE-78",
    message: "subprocess with shell=True. Command injection if input is user-controlled.",
    remediation: "Remove shell=True and pass command as a list: subprocess.run(['cmd', 'arg1'])",
    languages: ["python"],
  },
  {
    id: "PY_OS_POPEN",
    regex: /os\.popen\s*\(/,
    severity: "high",
    category: "injection",
    cweId: "CWE-78",
    message: "os.popen() is deprecated and runs through shell. Injection risk.",
    remediation: "Use subprocess.run() with shell=False instead.",
    languages: ["python"],
  },

  // Insecure Deserialization (Python)
  {
    id: "PY_PICKLE_LOAD",
    regex: /pickle\.(?:loads?|Unpickler)\s*\(/,
    severity: "critical",
    category: "dangerous-functions",
    cweId: "CWE-502",
    message: "pickle deserialization executes arbitrary code. Never unpickle untrusted data.",
    remediation: "Use JSON, MessagePack, or Protocol Buffers for untrusted data. Use hmac to verify pickle integrity if required.",
    languages: ["python"],
  },
  {
    id: "PY_YAML_LOAD",
    // The lookahead has to sit at the opening paren. Placed after `[^)]*`, the
    // engine backtracks that quantifier until the lookahead is satisfied, so
    // the rule fired on the safe form it was written to allow.
    regex: /yaml\.load\s*\((?![^)]*Loader\s*=\s*yaml\.(?:Safe|CSafe|Base)Loader)/,
    severity: "critical",
    category: "dangerous-functions",
    cweId: "CWE-502",
    message: "yaml.load() without SafeLoader allows arbitrary code execution.",
    remediation: "Use yaml.safe_load() or yaml.load(data, Loader=yaml.SafeLoader).",
    languages: ["python"],
  },
  {
    id: "PY_MARSHAL_LOADS",
    regex: /marshal\.loads?\s*\(/,
    severity: "high",
    category: "dangerous-functions",
    cweId: "CWE-502",
    message: "marshal.loads() can execute code. Not safe for untrusted data.",
    remediation: "Use JSON for data interchange. marshal is for internal Python use only.",
    languages: ["python"],
  },

  // Eval / Exec (Python)
  {
    id: "PY_EVAL",
    regex: /(?<!\w)eval\s*\(\s*(?:request\.|input\(|f['"]|.*?\+)/,
    severity: "critical",
    category: "dangerous-functions",
    cweId: "CWE-95",
    message: "Python eval() with dynamic input. Arbitrary code execution.",
    remediation: "Use ast.literal_eval() for safe evaluation of literal expressions. Never eval user input.",
    languages: ["python"],
  },
  {
    id: "PY_EXEC",
    regex: /(?<!\w)exec\s*\(\s*(?:request\.|input\(|f['"]|.*?\+)/,
    severity: "critical",
    category: "dangerous-functions",
    cweId: "CWE-95",
    message: "Python exec() with dynamic input. Full code execution.",
    remediation: "Avoid exec() entirely. Use structured data and predefined functions instead.",
    languages: ["python"],
  },
  {
    id: "PY_COMPILE",
    // The guard PY_EVAL and PY_EXEC already use. Without it re.compile(f"...")
    // matched, and an f-string regex is ordinary Python.
    regex: /(?<![\w.])compile\s*\(\s*(?:request\.|input\(|f['"])/,
    severity: "high",
    category: "dangerous-functions",
    cweId: "CWE-95",
    message: "compile() with user input can lead to code execution when used with exec/eval.",
    remediation: "Do not compile user-supplied code strings.",
    languages: ["python"],
  },

  // XSS / Template Injection (Python)
  {
    id: "PY_JINJA2_AUTOESCAPE_OFF",
    regex: /(?:Environment|Jinja2)\s*\([^)]*autoescape\s*=\s*False/i,
    severity: "high",
    category: "xss",
    cweId: "CWE-79",
    message: "Jinja2 autoescape disabled. Templates will render raw HTML, enabling XSS.",
    remediation: "Set autoescape=True: Environment(autoescape=True) or use select_autoescape().",
    languages: ["python"],
  },
  {
    id: "PY_MARKUPSAFE_SKIP",
    regex: /Markup\s*\(\s*(?:request\.|f['"]|.*?\+|.*?\.format\()/,
    severity: "high",
    category: "xss",
    cweId: "CWE-79",
    message: "Markup() with user input bypasses Jinja2 autoescaping. XSS risk.",
    remediation: "Only use Markup() with trusted, sanitized content. Use escape() on user input.",
    languages: ["python"],
  },
  {
    id: "PY_FLASK_RENDER_STRING",
    regex: /render_template_string\s*\(\s*(?:request\.|f['"]|.*?\+)/,
    severity: "critical",
    category: "xss",
    cweId: "CWE-79",
    message: "Flask render_template_string() with user input. Server-side template injection (SSTI).",
    remediation: "Use render_template() with a file. Never pass user input to render_template_string().",
    languages: ["python"],
  },

  // Django-specific
  {
    id: "PY_DJANGO_DEBUG",
    regex: /DEBUG\s*=\s*True/,
    severity: "high",
    category: "miscellaneous",
    cweId: "CWE-489",
    message: "Django DEBUG=True. Exposes stack traces, settings, and SQL queries in production.",
    remediation: "Set DEBUG=False in production. Use environment variables: DEBUG = os.environ.get('DEBUG', 'False') == 'True'",
    languages: ["python"],
  },
  {
    id: "PY_DJANGO_SECRET_KEY_HARDCODED",
    regex: /SECRET_KEY\s*=\s*['"][^'"]{10,}['"]/,
    severity: "high",
    category: "secrets",
    cweId: "CWE-798",
    message: "Django SECRET_KEY hardcoded. Used for signing sessions, tokens, and password resets.",
    remediation: "Use: SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')",
    languages: ["python"],
    matchScope: "literal",
  },
  {
    id: "PY_DJANGO_CSRF_EXEMPT",
    regex: /@csrf_exempt/,
    severity: "medium",
    category: "miscellaneous",
    cweId: "CWE-352",
    message: "Django @csrf_exempt disables CSRF protection on this view.",
    remediation: "Remove @csrf_exempt unless this is a public API endpoint with alternative auth (e.g., JWT).",
    languages: ["python"],
  },
  {
    id: "PY_DJANGO_ALLOWED_HOSTS_WILDCARD",
    regex: /ALLOWED_HOSTS\s*=\s*\[?\s*['"]?\*['"]?\s*\]?/,
    severity: "medium",
    category: "miscellaneous",
    cweId: "CWE-16",
    message: "Django ALLOWED_HOSTS = ['*']. Accepts requests for any hostname. Host header poisoning risk.",
    remediation: "Set specific hostnames: ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com']",
    languages: ["python"],
    matchScope: "literal",
  },

  // Flask-specific
  {
    id: "PY_FLASK_DEBUG",
    regex: /app\.run\s*\([^)]*debug\s*=\s*True/i,
    severity: "high",
    category: "miscellaneous",
    cweId: "CWE-489",
    message: "Flask debug mode enabled. Exposes interactive debugger with code execution in production.",
    remediation: "Set debug=False in production. Use: app.run(debug=os.environ.get('FLASK_DEBUG', False))",
    languages: ["python"],
  },
  {
    id: "PY_FLASK_SECRET_KEY_HARDCODED",
    regex: /app\.secret_key\s*=\s*['"][^'"]{4,}['"]/,
    severity: "high",
    category: "secrets",
    cweId: "CWE-798",
    message: "Flask secret_key hardcoded. Used for session signing.",
    remediation: "Use: app.secret_key = os.environ.get('FLASK_SECRET_KEY')",
    languages: ["python"],
    matchScope: "literal",
  },

  // Path Traversal (Python)
  {
    id: "PY_OPEN_USER_INPUT",
    regex: /open\s*\(\s*(?:request\.|f['"]|.*?\+\s*(?:request|input|user|param))/i,
    severity: "high",
    category: "path-traversal",
    cweId: "CWE-22",
    message: "Python open() with user input. Path traversal allows reading arbitrary files.",
    remediation: "Validate path with os.path.realpath() and check it starts with allowed directory.",
    languages: ["python"],
  },
  {
    id: "PY_SEND_FILE_USER_INPUT",
    regex: /send_file\s*\(\s*(?:request\.|f['"]|.*?\+\s*(?:request|input|user))/i,
    severity: "high",
    category: "path-traversal",
    cweId: "CWE-22",
    message: "Flask send_file() with user input. Arbitrary file download risk.",
    remediation: "Use send_from_directory() with a fixed directory: send_from_directory('/safe/dir', filename)",
    languages: ["python"],
  },

  // Weak Crypto (Python)
  {
    id: "PY_HASHLIB_MD5",
    regex: /hashlib\.md5\s*\(/,
    severity: "high",
    category: "crypto",
    cweId: "CWE-328",
    message: "MD5 via hashlib. Broken for security purposes.",
    remediation: "Use hashlib.sha256() for integrity. Use bcrypt/argon2 for passwords.",
    languages: ["python"],
  },
  {
    id: "PY_HASHLIB_SHA1",
    regex: /hashlib\.sha1\s*\(/,
    severity: "medium",
    category: "crypto",
    cweId: "CWE-328",
    message: "SHA-1 via hashlib. Known collision attacks.",
    remediation: "Use hashlib.sha256() or hashlib.sha3_256().",
    languages: ["python"],
  },
  {
    id: "PY_RANDOM_SECURITY",
    regex: /(?<!\w)random\.(?:random|randint|choice|randrange)\s*\(/,
    severity: "medium",
    category: "crypto",
    cweId: "CWE-338",
    message: "Python random module is not cryptographically secure.",
    remediation: "Use secrets module: secrets.token_hex(), secrets.randbelow(), secrets.choice().",
    languages: ["python"],
  },

  // Auth (Python)
  {
    id: "PY_JWT_NO_VERIFY",
    regex: /jwt\.decode\s*\([^)]*(?:verify\s*=\s*False|options\s*=\s*\{[^}]*"verify_signature"\s*:\s*False)/i,
    severity: "critical",
    category: "auth",
    cweId: "CWE-347",
    message: "PyJWT decode with verification disabled. Tokens can be forged.",
    remediation: "Always verify: jwt.decode(token, key, algorithms=['HS256']). Never disable verification.",
    languages: ["python"],
    matchScope: "literal",
  },
  {
    id: "PY_ASSERT_SECURITY",
    regex: /assert\s+(?:request\.|user\.|is_admin|is_authenticated|has_perm)/,
    severity: "high",
    category: "auth",
    cweId: "CWE-617",
    message: "assert for security checks. assert is stripped in optimized mode (-O flag).",
    remediation: "Use if/raise instead: if not user.is_admin: raise PermissionError('Unauthorized')",
    languages: ["python"],
  },
];
